// ============================================================
// ゲームデータ（GUTS MONSTERS）
//   モンスター・技・アイテム・マップ・イベント・冒険ノート
// ============================================================
const DATA = {
  TYPES: TYPE_CHART,

  MOVES: {
    'たいあたり':   { type: 'ノーマル', power: 35, pp: 35 },
    'ひっかく':     { type: 'ノーマル', power: 40, pp: 30 },
    'かみつく':     { type: 'ノーマル', power: 45, pp: 25 },
    'はっぱカッター': { type: 'くさ',   power: 45, pp: 25 },
    'ひのこ':       { type: 'ほのお',   power: 40, pp: 25 },
    'あまごい':     { type: 'みず',     power: 40, pp: 25 },
    'でんきショック': { type: 'でんき', power: 40, pp: 25 },
    'かぜおこし':   { type: 'かぜ',     power: 40, pp: 30 },
    'すなかけ':     { type: 'じめん',   power: 40, pp: 30 },
    'ひかりのつぶ': { type: 'ひかり',   power: 40, pp: 25 },
    'かげうち':     { type: 'やみ',     power: 40, pp: 25 },
  },

  // 御三家（Lv7スタート、Lv14・Lv28で進化：進化は未実装）
  // MONSTERS は DEX（js/dex.js）から生成。stage でステータスを決め、下の TUNED で個別に上書き。
  MONSTERS: (() => {
    const STAGE_BASE = { 1: { hp: 45, atk: 48, def: 46, spd: 48 }, 2: { hp: 60, atk: 63, def: 60, spd: 62 }, 3: { hp: 80, atk: 85, def: 80, spd: 80 } };
    const TUNED = {
      kokegame:   { base: { hp: 50, atk: 45, def: 55, spd: 38 }, desc: '甲羅が ゴルフボールみたいな 小さなリクガメ。\n苔が生えていて ちょっと ねむそう' },
      hinoshishi: { base: { hp: 44, atk: 54, def: 42, spd: 52 }, desc: '背中に ディンプルもようの イノシシのこ。\nしっぽの先に 小さな炎' },
      amepiyo:    { base: { hp: 46, atk: 45, def: 48, spd: 55 }, desc: '頭に 雨粒をのせた 黄色いヒヨコ。\n雨の日だけ やけに テンションが高い' },
      morigame:   { desc: '背中に 草木が育ちはじめたカメ' }, nushigame: { desc: '大樹を背負う 森の主' },
      shishiburn: { desc: '炎のたてがみを持つ 勇猛なイノシシ' }, shishivolke: { desc: '火山のような力を宿す 最終形態' },
      amegamo:    { desc: '雨をまとったカモ' }, doshagamo: { desc: '豪雨を呼ぶ 大きなカモ' },
      bubu:       { base: { hp: 50, atk: 55, def: 50, spd: 45 }, desc: '王冠をかぶった ちょっと悪そうな フレンチブルドッグ' },
      mantou:     { desc: 'いつも そばにいる ふわふわの相棒' },
    };
    const out = {};
    const on = id => !DEX_ENABLED || DEX_ENABLED.includes(id);
    for (const d of DEX) {
      if (!on(d.id)) continue;
      const t = TUNED[d.id] || {};
      const evo = d.evo && on(d.evo[0]) ? d.evo : null;   // 進化先が無効なら進化しない
      out[d.id] = { name: d.name, type: d.type, no: d.no, stage: d.stage, evo, special: !!d.special,
        base: t.base || STAGE_BASE[d.stage], moves: TYPE_MOVES[d.type], desc: t.desc || `${d.type}タイプの GUTS MONSTER` };
    }
    return out;
  })(),
  STARTERS: ['kokegame', 'hinoshishi', 'amepiyo'],

  // ---- BGM（assets/bgm/README_BGM.txt 参照）----
  BGM: {
    town:  'assets/bgm/guts_town.mp3',       // GUTS TOWN 112BPM
    lab:   'assets/bgm/okumura_lab.mp3',     // OKUMURA LAB 96BPM
    wild:  'assets/bgm/wild_adventure.mp3',  // A: ADVENTURE 156BPM（野生戦）
    rival: 'assets/bgm/rival_battle.mp3',    // RIVAL BATTLE 168BPM（ノブオ戦）
  },

  ITEMS: {
    'きずぐすり': { heal: 20, desc: 'なかまの HPを 20 かいふくする くすり。' },
    'ガッツボール': { ball: 1, desc: 'やせいの モンスターに なげて つかまえる。HPを へらすほど つかまえやすい。' },
  },
  // 捕まえやすさ（進化段階ごと。special はレア）
  CATCH_RATE: { 1: 0.75, 2: 0.45, 3: 0.25, special: 0.2 },

  // ---- 冒険ノート（フラグ順に上から判定）----
  NOTES: [
    { flag: 'kaedeWin',    text: 'ガーデンCCの クラブ認定を もらった。つぎは シブヤタウンへ。（つづきは じゅんびちゅう）' },
    { flag: 'trainerGoro', text: '会員 3人に 勝った。クラブハウス 右おくの チャンピオンルームで カエデと 公式戦。' },
    { flag: 'gardenSound', text: '18番ホールで 地下の音を 確認した。クラブハウスの チャンピオンルームへ。会員 3人に 勝って カエデに 会おう。' },
    { flag: 'deviceGiven', text: 'カエデと コースを 調査。コースを 奥まで すすんで 18番ホールを しらべよう。' },
    { flag: 'ccIn',     text: 'ガーデンCCに ついた。正門前の カエデに 観測機を とどけよう。' },
    { flag: 'town2',    text: 'ガーデンプレースに ついた。町の北の ガーデンCCに いる カエデに 観測機を とどけよう。' },
    { flag: 'forestIn', text: 'グリーンの森を 北へ ぬけて ガーデンプレースへ。' },
    { flag: 'rival1',  text: '町の北の ガーデンロードへ 向かおう。' },
    { flag: 'device',  text: '観測機を ガーデンCCの カエデに とどけよう。町の北から ガーデンロードへ。' },
    { flag: 'starter', text: '研究所を出て 冒険をはじめよう。' },
    { flag: null,      text: '冒険の朝だ。家を出て、オクムラ博士の研究所へ向かおう。' },
  ],

  // ---- タイル ----
  // 屋外: G芝 T草むら（ラフ） F花 W木 P道（カート道） ~水 B橋 #壁 N窓 R屋根 ^屋根端 D扉 S看板 =柵 L街灯 H生垣
  // ゴルフ場: gフェアウェイ nグリーン Kバンカー Yピンフラッグ yティーマーカー
  // 屋内: .床 X壁 b寝台 t TV d机 s棚 p植物 m出口マット c絨毯 M装置 C受付 O台
  TILE_ART: {
    G: 'grass', T: 'tall', F: 'flower', W: 'tree', P: 'path', '~': 'water', B: 'bridge',
    '#': 'wall', N: 'window', R: 'roof', '^': 'roof_edge', D: 'door', S: 'sign', '=': 'fence', L: 'lamp', H: 'hedge',
    A: 'lab_roof', a: 'lab_roof_dish', E: 'lab_wall', e: 'lab_window', J: 'lab_logo', I: 'lab_door',
    '.': 'floor', X: 'wallin', b: 'bed', t: 'tv', d: 'desk', s: 'shelf', p: 'plant', m: 'mat', c: 'carpet', M: 'machine', C: 'counter', O: 'table',
  },
  WALKABLE: new Set(['G', 'T', 'F', 'P', 'B', 'D', 'I', 'Q', '.', 'm', 'c', 'g', 'n', 'K', 'y']),   // 一枚絵マップの '#' は進めない
  // 置き物（タイル画像の名前）：w,h はマス数、door は左上からのドアの位置（そこだけ通れる）
  OBJECTS: { in_machine: { w: 2, h: 2, door: [-1, -1] }, in_table: { w: 3, h: 2, door: [-1, -1] }, house: { w: 5, h: 3, door: [2, 2] }, house2: { w: 5, h: 3, door: [2, 2] }, heal: { w: 5, h: 3, door: [2, 2] }, shop: { w: 5, h: 3, door: [2, 2] }, lab: { w: 11, h: 7, door: [5, 6] }, golfguts: { w: 11, h: 7, door: [5, 6] } },
  VOID_ART: 'wallin',

  MAPS: {
    home: {
      name: 'じぶんの いえ', indoor: true, bgm: 'town',
      rows: [
        'XXXXXXXXXX',
        'X.b..s.t.X',
        'X........X',
        'X.d......X',
        'X........X',
        'Xp.......X',
        'X....m...X',
        'XXXXXXXXXX',
      ],
      events: [
        { x: 5, y: 6, kind: 'warp', to: { map: 'town', x: 17, y: 6, dir: 'down' } },
        { x: 2, y: 1, kind: 'look', text: 'じぶんの ベッド。\nきょうは よく ねむれた。' },
        { x: 7, y: 1, kind: 'look', text: 'テレビ。ゴルフ中継が ながれている。' },
        { x: 2, y: 3, kind: 'look', text: 'つくえ。ゴルフの スコアカードが おいてある。' },
        { x: 5, y: 1, kind: 'look', text: 'ほん棚。「はじめての モンスター育成」' },
      ],
    },
    town: {
      name: 'ガッツタウン', bgm: 'town',
      // 36×22。研究所は左上、GOLF GUTS は右上、北出口（ガーデンロード）は中央の縦道の上端
      rows: [
        'WWWWWWWWWWWWWPWWWWWWWWWWWWWWWWWWWWWW',
        'WGGGGGGGGGGGSPGGGGGGGGGGGGGGGGGGGGGW',
        'WGGGGGGGGGGGGPGGGGGGGGGGGGGGGGGGGGGW',
        'WGGGGGGGGGGGGPGGGGGGGGGGGGGGGGGGGGGW',
        'WGGGGGGGGGGGGPGGGGGGGGGGGGGGGGGGGGGW',
        'WGGGGGGGGGGGGPGGGGGGGGGGGGGGGGGGGGGW',
        'WGGGGGGGGGGGGPGGGPGGGGGGGGGGGGGGGGGW',
        'WGGGGGGGGGGGGPGGGPGGGGGGGGGGGGGGGGGW',
        'WGHHHHPHHHHGGPGGGPGSGGGGGGGGGPGGGGGW',
        'WGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGW',
        'WGGGGGGGGGGGGPGGGGGGGLGGGGGGGGGGGGGW',
        'WGGGGGGGGSGGGPGGGGGGGGGGGGGGGGGGGGGW',
        'WGGGGGGGFGGGGPGGGGGGGGGGGGGGFFGGGGGW',
        'WGGGGGGGGGGGGPGGGGGGGGGGGGGGGGGGGGGW',
        'WGGGGGGGGGGGGPGGGGGGGGGGGGGGGGGGFFGW',
        'WGGGPGGGGGGGGPGGGPGGGGGGGGGGGGGGGGGW',
        'WGPPPPPPPPPPPPPPPPPPPPPPGGGGGGGGGGGW',
        'WGGGGGGGGGGGGPGGGGGG~~~GGGGGGGGGGGGW',
        'WGFFGGHHHHGGGPGGGGGG~~~GGGGGFFGGGGGW',
        'WGGGGGGGGGGGGPGGGGGGGGFFGGGGGGGGFFGW',
        'WGGGGGGGGGGGGPGGGGGGGGGGGGGGGGGGGGGW',
        'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
      ],
      objects: [
        { sprite: 'lab', x: 1, y: 1 },
        { sprite: 'house', x: 15, y: 3 },
        { sprite: 'heal', x: 2, y: 12 }, { sprite: 'shop', x: 15, y: 12 },
        { sprite: 'golfguts', x: 24, y: 1 },
      ],
      events: [
        { x: 17, y: 5, kind: 'warp', to: { map: 'home', x: 5, y: 5, dir: 'up' } },
        { x: 6, y: 7, kind: 'warp', to: { map: 'lab', x: 8, y: 8, dir: 'up' } },
        { x: 4, y: 14, kind: 'warp', to: { map: 'heal', x: 4, y: 4, dir: 'up' } },
        { x: 17, y: 14, kind: 'warp', to: { map: 'shop', x: 4, y: 4, dir: 'up' } },
        { x: 29, y: 7, kind: 'warp', to: { map: 'golfguts', x: 14, y: 17, dir: 'up' } },
        { x: 13, y: 0, kind: 'warp', to: { map: 'road', x: 7, y: 20, dir: 'up' } },
        { x: 9, y: 11, kind: 'sign', text: 'ガッツタウン\nゴルフ場の となりの しずかな町' },
        { x: 12, y: 1, kind: 'sign', text: 'この先 ガーデンロード\nガーデンプレースまで つづく' },
        { x: 19, y: 8, kind: 'sign', text: 'オクムラ モンスター研究所は\n町の 北西' },
        { x: 15, y: 10, kind: 'npc', img: 'v22', sprite: 'npc_woman', dir: 'down',
          text: '北の ガーデンロードには\nやせいの ガッツモンスターが いるのよ。' },
        { x: 20, y: 6, kind: 'npc', img: 'v23', sprite: 'npc_man', dir: 'down',
          text: 'この帽子は ゴルフ場の 売店で かった。\n日ざしが つよい日に ちょうどいい。' },
        { x: 5, y: 17, kind: 'npc', img: 'v21', sprite: 'npc_woman', dir: 'right',
          text: 'おかあさんが いってたわ。\n「よるは モンスターが げんきになる」って。' },
        { x: 8, y: 19, kind: 'npc', img: 'v01', sprite: 'npc_man', dir: 'right',
          text: 'ここの 芝は ゴルフ場と おなじ\n手入れを しているんだ。' },
        // 町の北出口の手前：御三家をもらう前は引き返す／もらった後はノブオが下から来て勝負
        { x: 13, y: 1, kind: 'trigger', id: 'townExit' },
      ],
    },
    golfguts: {
      name: 'GOLF GUTS', indoor: true, bgm: 'lab', image: 'assets/maps/golfguts_room.png',
      // 一枚絵マップ（ChatGPT製 assets/src/golfguts_room_src.png → 480×320 ドット、30×20 マス）。rows は当たり判定だけ（# 進めない . 床 C カウンター（越しに話せる） m 出入口）
      // 左：打席ブース×4、奥：受付・ロッカー・クラブラック、右：シミュレーター×2、手前：ラウンジとパター練習グリーン
      rows: [
        '##############################',
        '##############################',
        '###########.......############',
        '######.....#################.#',
        '######.....CCCCCCCC....#######',
        '######.................#######',
        '######.................#######',
        '######.................#######',
        '######.................#######',
        '######.................#######',
        '######.................#######',
        '######.................#######',
        '######.................#######',
        '######.................#######',
        '######.................#######',
        '#.................##########.#',
        '###.########......############',
        '###.########......############',
        '##############mm##############',
        '##############################',
      ],
      objects: [],
      events: [
        { x: 14, y: 18, kind: 'warp', to: { map: 'town', x: 29, y: 8, dir: 'down' } },
        { x: 15, y: 18, kind: 'warp', to: { map: 'town', x: 29, y: 8, dir: 'down' } },
        // GOLF GUTS の4人（正面向きで1列。セリフは仮）
        { x: 12, y: 9, kind: 'npc', img: 'hori', sprite: 'npc_man', dir: 'down', name: 'ホリ',
          text: 'おれは ホリ。\nスイングは リズムが いのちだ。' },
        { x: 13, y: 9, kind: 'npc', img: 'kuga', sprite: 'npc_man', dir: 'down', name: 'クガ',
          text: 'クガだ。\nまずは グリップから みなおせ。' },
        { x: 14, y: 9, kind: 'npc', img: 'bunta', sprite: 'npc_man', dir: 'down', name: 'ブンタ',
          text: 'ブンタっていうんだ。\nここで 毎日 ボールを うってる。' },
        { x: 15, y: 9, kind: 'npc', img: 'shinji', sprite: 'npc_man', dir: 'down', name: 'シンジ',
          text: 'シンジです。\nパターは きもちで うつもんだよ。' },
        { x: 7, y: 2, kind: 'look', text: 'ホワイトボード。\nスイングの 図が かいてある。' },
        { x: 6, y: 2, kind: 'look', text: 'モニターに コースの 映像が ながれている。' },
        { x: 21, y: 2, kind: 'look', text: 'ロッカー。\nかぎが かかっている。' },
        { x: 25, y: 2, kind: 'look', text: 'ゴルフクラブが ずらりと ならんでいる。' },
        { x: 2, y: 17, kind: 'look', text: 'ウォーターサーバー。\nつめたい 水が のめる。' },
        { x: 22, y: 16, kind: 'look', text: 'パターの 練習グリーン。\nカップが 2つ ある。' },
        { x: 3, y: 4, kind: 'look', text: '打席ブース。\nネットに むかって ボールを うつ。' },
        { x: 25, y: 7, kind: 'look', text: 'ゴルフシミュレーター。\nスクリーンに コースが うつっている。' },
      ],
    },
    lab: {
      name: 'オクムラ研究所', indoor: true, bgm: 'lab', image: 'assets/maps/lab_room.png',
      // 一枚絵マップ（ChatGPT製 assets/src/lab_room_src.png → 256×160 ドット、右へ 8 ドットずらして方眼に合わせた）。rows は当たり判定だけ（# 進めない . 床 m 出口マット）
      rows: [
        '################',
        '################',
        '###..........###',
        '#..###.....###.#',
        '####..#####..###',
        '####..#####..###',
        '####.........###',
        '######.....#####',
        '###...........##',
        '########m#######',
      ],
      objects: [],
      events: [
        { x: 8, y: 9, kind: 'warp', to: { map: 'town', x: 6, y: 8, dir: 'down' } },
        { x: 8, y: 3, kind: 'npc', img: 'npc_prof', sprite: 'npc_prof', dir: 'down', name: 'オクムラ博士', prof: true },
        // 机の台座（絵の位置に合わせてボールをずらして描く）
        // 机の台座（マスの中央に置く。えらんだボールだけ消える：flags.starterId）。pick：えらぶときのせりふ（2行ずつ3ページ、最後に はい／いいえ）
        { x: 7, y: 5, kind: 'starter', id: 'kokegame',   dy: -12,
          pick: ['いわのような こうらに\nコケを まとった ちいさな リクガメ。', 'のんびりやだけど\nとっても がまんづよい。', 'この コケガメを\nはじめての なかまに しますか？'] },
        { x: 8, y: 5, kind: 'starter', id: 'hinoshishi', dy: -12,
          pick: ['あたまと しっぽに\nほのおを ともした ちいさな イノシシ。', 'まけずぎらいで\nつよい あいてほど もえてくる。', 'この ヒノシシを\nはじめての なかまに しますか？'] },
        { x: 9, y: 5, kind: 'starter', id: 'amepiyo',    dy: -12,
          pick: ['あたまに おおきな あまつぶを のせた\nあおと しろの ちいさな ヒヨコ。', 'あめが ふると\nいつもより げんきになる。', 'この アメピヨを\nはじめての なかまに しますか？'] },
        { x: 1, y: 2, kind: 'look', text: 'モンスターの データを しらべる 装置だ。' },
        { x: 2, y: 2, kind: 'look', text: 'モンスターの データを しらべる 装置だ。' },
        { x: 14, y: 2, kind: 'look', text: 'モンスターの エネルギーを はかる 装置。\nブーンと 音が している。' },
        { x: 15, y: 2, kind: 'look', text: 'モンスターの エネルギーを はかる 装置。\nブーンと 音が している。' },
        { x: 7, y: 1, kind: 'look', text: 'ホワイトボード。\nタイプ相性の 図が かいてある。' },
        { x: 9, y: 1, kind: 'look', text: 'ホワイトボード。\n「ガーデンCC 調査」と かいてある。' },
        { x: 4, y: 1, kind: 'look', text: '研究ノートが ぎっしり。' },
        { x: 5, y: 1, kind: 'look', text: '研究ノートが ぎっしり。' },
        { x: 11, y: 1, kind: 'look', text: 'モンスター図鑑の 古い版が ならんでいる。' },
        { x: 12, y: 1, kind: 'look', text: 'モンスター図鑑の 古い版が ならんでいる。' },
        { x: 4, y: 3, kind: 'look', text: '博士の パソコン。\nモンスターの 写真が ならんでいる。' },
        { x: 12, y: 3, kind: 'look', text: '助手の パソコン。\nデータの 入力ちゅう…。' },
        { x: 4, y: 7, kind: 'look', text: 'パソコン。 スクリーンセーバーが\nぐるぐる まわっている。' },
        { x: 12, y: 7, kind: 'look', text: 'パソコン。 ゴルフ場の 地図が\nひらいてある。' },
        { x: 2, y: 4, kind: 'look', text: 'ガラスケースの 中に\nガッツボールが ならんでいる。' },
        { x: 13, y: 4, kind: 'look', text: 'ガラスケースの 中に\nガッツボールが ならんでいる。' },
        { x: 2, y: 7, kind: 'look', text: 'ガラスケース。 からっぽだ。' },
        { x: 13, y: 7, kind: 'look', text: 'ガラスケース。 からっぽだ。' },
        { x: 1, y: 8, kind: 'look', text: '観葉植物。 みずみずしい。' },
        { x: 13, y: 2, kind: 'look', text: '観葉植物。 みずみずしい。' },
      ],
    },
    heal: {
      name: 'かいふくの いえ', indoor: true, bgm: 'town',
      rows: [
        'XXXXXXXXXX',
        'X........X',
        'X...s..p.X',
        'XCCCCCCCCX',
        'X........X',
        'X....m...X',
        'XXXXXXXXXX',
      ],
      events: [
        { x: 5, y: 5, kind: 'warp', to: { map: 'town', x: 4, y: 15, dir: 'down' } },
        { x: 4, y: 2, kind: 'npc', img: 'v12', sprite: 'npc_nurse', dir: 'down', heal: true, name: 'うけつけ',
          text: 'ようこそ かいふくの いえへ。\nなかまを げんきに してあげますね。' },
      ],
    },
    shop: {
      name: 'ショップ', indoor: true, bgm: 'town',
      rows: [
        'XXXXXXXXXX',
        'X........X',
        'X..s...s.X',
        'XCCCCCCCCX',
        'X........X',
        'X....m...X',
        'XXXXXXXXXX',
      ],
      events: [
        { x: 5, y: 5, kind: 'warp', to: { map: 'town', x: 17, y: 15, dir: 'down' } },
        { x: 4, y: 2, kind: 'npc', img: 'v25', sprite: 'npc_woman', dir: 'down', name: 'てんいん', shop: true,
          text: 'いらっしゃい！\nきずぐすりなら さしあげますよ。（ショップは じゅんびちゅう）' },
      ],
    },
    road: {
      name: 'ガーデンロード', bgm: 'town', battleBg: 'rough',   // ※専用曲は未提供のため町の曲を仮使用
      rows: [
        'WWWWWWWPWWWWWW',
        'WGGGGGSPGGGGGW',
        'WGGGGGGPGGFGGW',
        'WGGWGGGPGGGGGW',
        'WGTTTGGPGGWGGW',
        'WGTTTGGPGTTTGW',
        'WGTTTGGPGTTTGW',
        'WGGGGGGPGTTTGW',
        'WGFGGGGPGGGGGW',
        'WGGGGGGPGGGGGW',
        'W~~~~~~B~~~~~W',
        'W~~~~~~B~~~~~W',
        'WGGWGGGPGGGGGW',
        'WGGGGGGPGGTTGW',
        'WGTTTGGPGGTTGW',
        'WGTTGGGPGGGGGW',
        'WGGGGGGPGGWGGW',
        'WGGGGGGPGGSGGW',
        'WGFGGGGPGGGGGW',
        'WGGGGGGPGGGGGW',
        'WGGGGGGPGGGGGW',
        'WWWWWWWPWWWWWW',
      ],
      encounters: [
        { id: 'shibatta', level: [3, 5], weight: 4 }, { id: 'kokemogu', level: [3, 5], weight: 4 }, { id: 'nyakimi', level: [2, 4], weight: 3 }, { id: 'kinomushi', level: [2, 4], weight: 3 }, { id: 'bankani', level: [3, 5], weight: 3 },
      ],
      events: [
        { x: 7, y: 21, kind: 'warp', to: { map: 'town', x: 13, y: 1, dir: 'down' } },
        { x: 7, y: 0, kind: 'warp', to: { map: 'forest', x: 7, y: 26, dir: 'up' } },
        { x: 10, y: 17, kind: 'sign', text: 'ガーデンロード\n草むらに 注意' },
        { x: 6, y: 1, kind: 'sign', text: 'この先 グリーンの森\n森を ぬけると ガーデンプレース' },
        { x: 4, y: 9, kind: 'npc', img: 'v05', sprite: 'npc_man', dir: 'right',
          text: '草むらで つかまえた モンスターは\nなかまに なるんだ。（捕獲は 未実装）' },
      ],
    },
    forest: {
      name: 'グリーンの森', bgm: 'town', battleBg: 'rough', flagOnEnter: 'forestIn',
      rows: [
        'WWWWWWWWPWWWWWWW',
        'WWWGGGGGPGGWWWWW',
        'WWGGTTGGPGGGWWWW',
        'WWGTTTGGPGGTGWWW',
        'WWGGGGGGPGGTTGWW',
        'WWWGGGPPPGGGGWWW',
        'WWWWGGPGGGGWWWWW',
        'WWWGGGPGGGGGWWWW',
        'WWGGGGPGGTTGGWWW',
        'WWGTTGPPPGGGGGWW',
        'WWGTTGGGPGGGGGWW',
        'WWWGGGGGPGGSGWWW',
        'WWWW~~GGPGGGGWWW',
        'WWW~~~GGPGGGWWWW',
        'WWWW~GGGPGGGWWWW',
        'WWWGGGPPPGGGGWWW',
        'WWGGGGPGGGGTTGWW',
        'WWGTTGPGGGGTTGWW',
        'WWGTTGPGGGGGGWWW',
        'WWGGGGPGGWWGGWWW',
        'WWWGGGPPPGGGGWWW',
        'WWWWGGGGPGGGWWWW',
        'WWWGGGGGPGGGGWWW',
        'WWGGTTGGPGGGGGWW',
        'WWGGTTGGPGGGFGWW',
        'WWWGGGGGPGGGGWWW',
        'WWWWWGGPPGGWWWWW',
        'WWWWWWWPWWWWWWWW',
      ],
      encounters: [
        { id: 'kinomushi', level: [4, 6], weight: 4 }, { id: 'nyakimi', level: [4, 6], weight: 3 }, { id: 'kokemogu', level: [4, 6], weight: 3 },
        { id: 'kinomino', level: [6, 8], weight: 2 }, { id: 'nyakimino', level: [6, 8], weight: 2 }, { id: 'bubu', level: [5, 7], weight: 2 },
      ],
      events: [
        { x: 7, y: 27, kind: 'warp', to: { map: 'road', x: 7, y: 1, dir: 'down' } },
        { x: 8, y: 0, kind: 'warp', to: { map: 'town2', x: 9, y: 13, dir: 'up' } },
        { x: 11, y: 11, kind: 'sign', text: 'グリーンの森\n北へ ぬけると ガーデンプレース' },
        { x: 10, y: 4, kind: 'npc', img: 'v04', sprite: 'npc_man', dir: 'left',
          text: 'この森は キノムシが おおいんだ。\n虫は ほのおタイプに よわいぞ。' },
        { x: 9, y: 22, kind: 'npc', img: 'v24', sprite: 'npc_woman', dir: 'down',
          text: '森の中は 道が くねくね。\n道なりに 北へ すすめば ぬけられるわ。' },
      ],
    },
    town2: {
      name: 'ガーデンプレース', bgm: 'town', flagOnEnter: 'town2',
      // 北（中央の縦道の上）が庭園の入口
      rows: [
        'WWWWWWWWWPWWWWWWWWWW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WGGGPPPPPPPPPPPPPPGW',
        'WGFGGGGGGPGGGGGGLGGW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WGGGPPPPPPPPPPPPPPGW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WGGHHHGGGPGGG~~~GGGW',
        'WGFFGGGGGPGGG~~~GGGW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WWWWWWWWWPWWWWWWWWWW',
      ],
      objects: [
        { sprite: 'heal', x: 1, y: 1 }, { sprite: 'house2', x: 14, y: 1 },
        { sprite: 'shop', x: 1, y: 6 }, { sprite: 'house2', x: 14, y: 6 },
      ],
      events: [
        { x: 9, y: 14, kind: 'warp', to: { map: 'forest', x: 8, y: 1, dir: 'down' } },
        { x: 9, y: 0, kind: 'warp', to: { map: 'cc', x: 9, y: 13, dir: 'up' } },
        { x: 10, y: 1, kind: 'sign', text: 'この先 ガーデンカントリークラブ\nクラブハウス・コース入口' },
        // カエデ：観測機を渡すまでは庭園の入口（町側）にいる。渡したあとは庭園の中へ
        { x: 3, y: 3, kind: 'warp', to: { map: 'heal2', x: 4, y: 4, dir: 'up' } },
        { x: 16, y: 3, kind: 'warp', to: { map: 'house2', x: 5, y: 5, dir: 'up' } },
        { x: 3, y: 8, kind: 'warp', to: { map: 'shop2', x: 4, y: 4, dir: 'up' } },
        { x: 16, y: 8, kind: 'look', text: 'かぎが かかっている。\nるすの ようだ。' },
        { x: 8, y: 10, kind: 'sign', text: 'ガーデンプレース\n森の むこうの 小さな町' },
        { x: 7, y: 5, kind: 'npc', img: 'v18', sprite: 'npc_woman', dir: 'down',
          text: 'ガーデンプレースへ ようこそ。\n町の北の ゴルフ場は グリーンキーパーの\nカエデさんが 守っているのよ。' },
        { x: 4, y: 12, kind: 'npc', img: 'v26', sprite: 'npc_woman', dir: 'right',
          text: 'きのう 森で キノムシを みたの。\nとっても かわいかった！' },
        { x: 11, y: 7, kind: 'npc', img: 'v27', sprite: 'npc_man', dir: 'left',
          text: 'ガーデンCCの コースには\nやせいの モンスターが たくさん いる。\nつかまえるなら あそこだ！' },
        { x: 12, y: 11, kind: 'npc', img: 'v19', sprite: 'npc_man', dir: 'left',
          text: 'クラブハウスの チャンピオンに 勝てば\nクラブ認定が もらえるんだ。\nその前に 会員の 腕じまんが 待ってるぞ。' },
      ],
    },
    // ===== ガーデンカントリークラブ =====
    // cc：正門前の広場。上の建物がクラブハウス（ジム）、右上の門がコース（サファリ）入口。カエデは観測機を渡すまでここ
    cc: {
      name: 'ガーデンCC 正門', bgm: 'town', flagOnEnter: 'ccIn',
      // 巨大なクラブハウス（14×6マス）。コースへは クラブハウスの 奥の扉から
      rows: [
        'WWWWWWWWWWWWWWWWWWWW',
        'WGG^^^^^^^^^^^^^^GGW',
        'WGGRRRRRRRRRRRRRRGGW',
        'WGGRRRRRRRRRRRRRRGGW',
        'WGGN#N#N#N#N#N#N#GGW',
        'WGG#N#N#N#N#N#N#NGGW',
        'WGG##N###D###N###GGW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WGFGGGGGGPGGGGGGGFGW',
        'WGGGGPPPPPPPPPPPGGGW',
        'WGGGGPGGGPGGGGGPGGGW',
        'WGHHHPGGGPGLGGGPHHHW',
        'WGGGGGGGGPGGGGGGGGGW',
        'WWWWWWWWWPWWWWWWWWWW',
      ],
      events: [
        { x: 9, y: 13, kind: 'warp', to: { map: 'town2', x: 9, y: 1, dir: 'down' } },
        { x: 9, y: 6, kind: 'warp', to: { map: 'clubhouse', x: 8, y: 15, dir: 'up' } },
        { x: 11, y: 7, kind: 'sign', text: 'ガーデンカントリークラブ\nクラブハウス（コース入口は 館内の 奥）' },
        { x: 14, y: 8, kind: 'npc', img: 'v15', sprite: 'npc_woman', dir: 'left', name: 'カエデ', kaede: true, unless: 'deviceGiven' },
        { x: 14, y: 8, kind: 'npc', img: 'v15', sprite: 'npc_woman', dir: 'left', name: 'カエデ', kaede: true, if: 'deviceGiven', unless: 'gardenSound' },
        { x: 5, y: 12, kind: 'npc', img: 'v05', sprite: 'npc_man', dir: 'right', name: 'キャディ',
          text: 'コースへは クラブハウスを 通りぬけて\n奥の 扉から 出るんだ。\nカート道を はずれると モンスターが 出るぞ。' },
        { x: 3, y: 8, kind: 'npc', img: 'v27', sprite: 'npc_man', dir: 'right', name: '会員',
          text: 'クラブハウスの 中では 会員の\n腕じまん 3人が 待ちかまえている。\n全員に 勝たないと チャンピオンには 会えない。' },
      ],
    },
    // clubhouse：ジム兼コース入口。広いロビー。奥（上）の扉が コース、右上の扉が チャンピオンルーム
    clubhouse: {
      name: 'クラブハウス', indoor: true, bgm: 'lab',
      // 入口から 赤い通路が まっすぐ 奥へ。通路の先の扉が コース入口。フロントは 右側。チャンピオンルームは 左奥の扉
      rows: [
        'XXXXXXXXXXXXXXXXXXXXXXXX',
        'X.m.....m.....s.s....OpX',
        'X.......c..............X',
        'X.p.....c.....CCCCCCC..X',
        'X.......c..............X',
        'X.......c..............X',
        'X.d.....c........ss....X',
        'X.......c..............X',
        'X.p.....c......p.......X',
        'X.......c..............X',
        'X.......c..............X',
        'X.d.....c........d.....X',
        'X.......c..............X',
        'X.p.....c......p.......X',
        'X.......c..............X',
        'X.......c..............X',
        'X.......m..............X',
        'XXXXXXXXXXXXXXXXXXXXXXXX',
      ],
      events: [
        { x: 8, y: 16, kind: 'warp', to: { map: 'cc', x: 9, y: 7, dir: 'down' } },
        { x: 8, y: 1, kind: 'warp', to: { map: 'plaza', x: 9, y: 10, dir: 'up' } },
        { x: 2, y: 1, kind: 'warp', to: { map: 'champ', x: 4, y: 7, dir: 'up' }, needs: 'trainerGoro', waitText: '扉は しまっている。\n「会員 3名に 勝った者のみ」' },
        { x: 9, y: 1, kind: 'sign', text: '↑ コース入口\nラフ・バンカー・林に モンスター注意' },
        { x: 1, y: 2, kind: 'sign', text: 'チャンピオンルーム\n会員 3名に 勝った者のみ' },
        { x: 17, y: 2, kind: 'npc', img: 'v12', sprite: 'npc_nurse', dir: 'down', name: 'フロント', heal: true,
          text: 'ガーデンカントリークラブへ ようこそ。\nなかまを 休ませてから どうぞ。' },
        { x: 6, y: 5, kind: 'trainer', img: 'v27', sprite: 'npc_man', dir: 'right', name: '会員 タクマ', mon: 'shibatta', level: 6, flag: 'trainerTakuma',
          intro: 'オレが 一番手の タクマだ！\nクラブの 腕じまんを なめるなよ！', win: 'やるな… 二番手は この先だ。', lose: 'まだまだ。コースで きたえてこい。', after: 'チャンピオンの シバモグは 回復する。\nいっきに たたみかけろ。' },
        { x: 10, y: 9, kind: 'trainer', img: 'v18', sprite: 'npc_woman', dir: 'left', name: '会員 ミナ', mon: 'kinomino', level: 7, flag: 'trainerMina', needs: 'trainerTakuma',
          intro: '二番手の ミナよ。\nキノミノの かたい からだを くずせるかしら？', win: 'やられた… 三番手が 最後の 関門よ。', lose: 'まだ あまいわね。', after: 'カエデさんは くさタイプ。\nほのおや ひこうが きくわ。', wait: 'まずは タクマに 勝ってきて。' },
        { x: 6, y: 13, kind: 'trainer', img: 'v19', sprite: 'npc_man', dir: 'right', name: '会員 ゴロウ', mon: 'bankani', level: 8, flag: 'trainerGoro', needs: 'trainerMina',
          intro: '三番手の ゴロウだ。\nバンカニの はさみは 痛いぞ！', win: 'みごとだ！ チャンピオンルームの 扉が\nひらいた。左の おくだ。', lose: 'ふむ、出直してこい。', after: 'カエデさんに よろしくな。', wait: 'ミナに 勝ってからだ。' },
        { x: 16, y: 7, kind: 'npc', img: 'v04', sprite: 'npc_man', dir: 'left', name: '会員',
          text: 'コースの モンスターは 奥ほど 強い。\n池の ホールには みずタイプが いるぞ。' },
        { x: 18, y: 12, kind: 'npc', img: 'v24', sprite: 'npc_woman', dir: 'left', name: '会員',
          text: 'ガッツボールが たりなくなったら\nコースに 落ちてるのを さがすといいわ。' },
        { x: 21, y: 1, kind: 'look', text: 'トロフィーの 台。\n「クラブ選手権 優勝 カエデ」' },
        { x: 14, y: 1, kind: 'look', text: 'スコアカードが ならんでいる。\n認定スタンプを 押す 欄が ある。' },
        { x: 16, y: 1, kind: 'look', text: 'クラブの 歴史。 むかしは\nここも 野生の モンスターの 森だったらしい。' },
        { x: 2, y: 6, kind: 'look', text: 'コース図。 18番ホールに\n赤い ×印が ついている。' },
        { x: 17, y: 6, kind: 'look', text: '会員名簿。 いちばん上に\n「カエデ」と ある。' },
        { x: 17, y: 11, kind: 'look', text: 'ゴルフクラブの 試打コーナー。\nいまは だれも いない。' },
      ],
    },
    champ: {
      name: 'チャンピオンルーム', indoor: true, bgm: 'lab',
      rows: [
        'XXXXXXXXXX',
        'X.p.ss.p.X',
        'X........X',
        'X...cc...X',
        'X...cc...X',
        'X........X',
        'X........X',
        'X...m....X',
        'XXXXXXXXXX',
      ],
      events: [
        { x: 4, y: 7, kind: 'warp', to: { map: 'clubhouse', x: 2, y: 2, dir: 'down' } },
        { x: 4, y: 2, kind: 'npc', img: 'v15', sprite: 'npc_woman', dir: 'down', name: 'カエデ', kaede: true, champ: true },
        { x: 4, y: 1, kind: 'look', text: 'クラブ選手権の 大きな トロフィー。' },
      ],
    },
    // ===== コース（サファリ）：4エリア。奥ほど強い。カート道（P）は安全、T ラフ・K バンカー・W の林ぎわで出る =====
    // スタート広場：クラブハウスの奥の扉を出たところ。左が西コース、右が林間コース
    plaza: {
      golf: true, name: 'ガーデンCC スタート広場', bgm: 'town', battleBg: 'rough', flagOnEnter: 'courseIn',
      rows: [
        'WWWWWWWWWWWWWWWWWWWW',
        'WTTTTgggggggggTTTTTW',
        'WTTTgggnnnnngggTTTTW',
        'WgTTgggnnYnnggggTTgW',
        'WggggggnnnnngggggggW',
        'WgFggggggggggggggFgW',
        'PPPPPPPPPPPPPPPPPPPP',
        'WggggggggPgggggggggW',
        'WgKKggSggPggggSgKKgW',
        'WgKKgggggPggggggKKgW',
        'WTTTTTgggPgggTTTTTTW',
        'WWWWWWWWWPWWWWWWWWWW',
      ],
      encounters: [ { id: 'shibatta', level: [3, 5], weight: 4 }, { id: 'kokemogu', level: [3, 5], weight: 4 }, { id: 'nyakimi', level: [3, 4], weight: 3 } ],
      bunker: [ { id: 'bankani', level: [3, 5], weight: 5 }, { id: 'kokemogu', level: [3, 5], weight: 2 } ],
      events: [
        { x: 9, y: 11, kind: 'warp', to: { map: 'clubhouse', x: 8, y: 2, dir: 'down' } },
        { x: 0, y: 6, kind: 'warp', to: { map: 'course1', x: 22, y: 7, dir: 'left' } },
        { x: 19, y: 6, kind: 'warp', to: { map: 'course3', x: 9, y: 16, dir: 'up' } },
        { x: 6, y: 8, kind: 'sign', text: '← 西コース（1〜3番）\\nやさしい コース' },
        { x: 14, y: 8, kind: 'sign', text: '→ 林間コース（7〜9番）\\nモンスターが 多い' },
        { x: 11, y: 7, kind: 'npc', img: 'v24', sprite: 'npc_woman', dir: 'left', name: 'キャディ',
          text: 'コースは ぐるっと 一周 できるわ。\\n左回りは やさしく、右回りは 手ごわい。\\nいちばん奥が 18番ホールよ。' },
        { x: 4, y: 5, kind: 'npc', img: 'v05', sprite: 'npc_man', dir: 'right', name: 'ゴルファー',
          text: 'カート道を 歩けば モンスターは 出ない。\\nつかまえたいなら ラフに 入るんだ。' },
      ],
    },
    // 丘コース（North-East）：高台とバンカー群。北の18番と 南の林間を つなぐ
    course5: {
      greens: [[8.1, 3.3, 3.5, 2.2]], golf: true, name: 'ガーデンCC 丘コース（10〜12番）', bgm: 'town', battleBg: 'rough',
      rows: [
        'WWWWWWWWWWWWWWWWWWWW',
        'WggggnnnnngTTTTTTTTW',
        'WgggnnnnnnnnTTKKTTTW',
        'PPPPnnnYnnnnggKKTTTW',
        'WggPnnnnnnnnggggTTTW',
        'WggPgnnnnngggTTTgTTW',
        'WggPPPPPPPPPPPPgggTW',
        'WgggggggggggggPgggTW',
        'WTKKKggggTTTggPgKKTW',
        'WTKKKggggTTTggPgKKTW',
        'WTKKKTTTTTTgggPgggTW',
        'WTTTSTTTKKggggPgggTW',
        'WTTTTTTTKKggggPgggTW',
        'WTTTTTTTgggPPPPgggTW',
        'WTTTTTTTgggPgggggTTW',
        'WWWWWWWWWWWPWWWWWWWW',
      ],
      encounters: [ { id: 'kokemogu', level: [6, 8], weight: 4 }, { id: 'shibatta', level: [6, 8], weight: 3 }, { id: 'nyakimi', level: [6, 8], weight: 2 }, { id: 'kinomushi', level: [6, 8], weight: 2 } ],
      bunker: [ { id: 'bankani', level: [6, 9], weight: 7 } ],
      events: [
        { x: 0, y: 3, kind: 'warp', to: { map: 'course4', x: 16, y: 13, dir: 'left' } },
        { x: 11, y: 15, kind: 'warp', to: { map: 'course3', x: 17, y: 1, dir: 'down' } },
        { x: 4, y: 11, kind: 'sign', text: '丘コース 10〜12番\\nバンカーに 注意。高台から 18番が 見える' },
        { x: 7, y: 2, kind: 'item', item: 'きずぐすり', n: 2, flag: 'c5heal', text: '高台の グリーンに きずぐすりが 2つ！' },
        { x: 16, y: 10, kind: 'npc', img: 'v04', sprite: 'npc_man', dir: 'left', name: 'ゴルファー',
          text: 'ここの バンカーは 深いぞ。\\nバンカニが うようよ いる。' },
      ],
    },
    course1: {
      golf: true, name: 'ガーデンCC 西コース（1〜3番）', bgm: 'town', battleBg: 'rough',
      rows: [
        'WWWWWWWWWWWWWWWWWWWPWWWW',
        'WggnnngggTTTTTTTgggPgggW',
        'WgnnYnnggTTTTTTTgggPgggW',
        'WggnnngggTTTTTTTgggPgggW',
        'WggggggggggggKKKgggPgggW',
        'WTTTgggggggggKKKgggPgTgW',
        'WTTTTggggggggKKKgggPgTTW',
        'WTTTTggPPPPPPPPPPPPPPPPP',
        'WTTTTggggggggggggggggggW',
        'WTTTTTgggggggTTTTggFgggW',
        'WTTTTTTggggggTTTTggggggW',
        'WTTKKTgTgTTTTTTTTgggnnnW',
        'WTTKKgggggTTTTTTgggnnYnW',
        'WTKKKggggggTTSTTTgggnnnW',
        'WTTgggygygggTTTTTTgggggW',
        'WWWWWWWWWWWWWWWWWWWWWWWW',
      ],
      encounters: [ { id: 'shibatta', level: [4, 6], weight: 4 }, { id: 'kokemogu', level: [4, 6], weight: 4 }, { id: 'nyakimi', level: [3, 5], weight: 3 }, { id: 'kinomushi', level: [3, 5], weight: 3 } ],
      bunker: [ { id: 'bankani', level: [4, 6], weight: 5 }, { id: 'kokemogu', level: [4, 6], weight: 2 } ],
      events: [
        { x: 23, y: 7, kind: 'warp', to: { map: 'plaza', x: 1, y: 6, dir: 'right' } },
        { x: 19, y: 0, kind: 'warp', to: { map: 'course2', x: 6, y: 17, dir: 'up' } },
        { x: 13, y: 13, kind: 'sign', text: '1番ホール PAR4\nラフと バンカーに モンスター注意' },
        { x: 9, y: 1, kind: 'item', item: 'ガッツボール', n: 2, flag: 'c1ball', text: 'ラフの 中に ガッツボールが 2つ 落ちていた！' },
        { x: 12, y: 8, kind: 'npc', img: 'v24', sprite: 'npc_woman', dir: 'down', name: 'キャディ',
          text: 'ここは 1番から 3番ホール。\n北の カート道を すすむと 池の ホールよ。' },
        { x: 20, y: 4, kind: 'npc', img: 'v04', sprite: 'npc_man', dir: 'left', name: 'ゴルファー',
          text: 'バンカーには バンカニが いる。\n砂に もぐって 待ちぶせしてるんだ。' },
      ],
    },
    course2: {
      golf: true, name: 'ガーデンCC 池コース（4〜6番）', bgm: 'town', battleBg: 'rough',
      rows: [
        'WWWWWWWWWWWWWWWWPWWWWW',
        'WgggggggggggggggPgggTW',
        'WgnnngggTTTgggggPgggTW',
        'WgnYngggTTTgggggPgggTW',
        'WgnnnggPPPPPPPPPPgggTW',
        'WggggggPgggg~~~~~~gTTW',
        'WggggggPgg~~~~~~~~~~TW',
        'WTgggggPg~~~~~~~~~~~TW',
        'WTTTgggPg~~~~TTT~~~~TW',
        'WTTTgggPg~~~~TTT~~~~TW',
        'WTTTTggPg~~~~TgT~~~~TW',
        'WTTTTggPg~~~~~B~~~~~TW',
        'WTTTTgggg~~~~~B~~~~~TW',
        'WTTTTgSgggggggPgggTTTW',
        'WTKKggggggggggPgggTTTW',
        'WTKKggPPPPPPPPPgggTTTW',
        'WTTgggPggggggggggTTTTW',
        'WTgggyPyggggggggTTTTTW',
        'WWWWWWPWWWWWWWWWWWWWWW',
      ],
      encounters: [ { id: 'shibatta', level: [5, 7], weight: 3 }, { id: 'nyakimi', level: [5, 7], weight: 3 }, { id: 'kokemogu', level: [5, 7], weight: 2 }, { id: 'kinomushi', level: [5, 7], weight: 2 } ],
      bunker: [ { id: 'bankani', level: [6, 8], weight: 6 } ],
      events: [
        { x: 6, y: 18, kind: 'warp', to: { map: 'course1', x: 19, y: 1, dir: 'down' } },
        { x: 16, y: 0, kind: 'warp', to: { map: 'course4', x: 1, y: 13, dir: 'right' } },
        { x: 6, y: 13, kind: 'sign', text: '4番ホール PAR3 池越え\n池の 中の 島に なにか ある？' },
        { x: 14, y: 9, kind: 'item', item: 'きずぐすり', n: 2, flag: 'c2heal', text: '池の 島に きずぐすりが 2つ！' },
        { x: 10, y: 1, kind: 'npc', img: 'v05', sprite: 'npc_man', dir: 'down', name: 'ゴルファー',
          text: '池の ほとりは モンスターが 多い。\n北へ ぬけると 18番ホールだ。' },
      ],
    },
    course3: {
      golf: true, name: 'ガーデンCC 林間コース（7〜9番）', bgm: 'town', battleBg: 'rough',
      rows: [
        'WWWWWWWWWWWWWWWWWPWW',
        'WWWTTTTTTTTTWWWWWPWW',
        'WWTTTTggKKggggWWWPWW',
        'WWTTTTggKKgggggggPgW',
        'WWTTgggggggggggggPgW',
        'WWWWggPPPPPPPPPPPPgW',
        'WWWgggPggggggggggggW',
        'WWTTTgPggWWWggTTTggW',
        'WWgTTgPggWWWggTTTgTW',
        'WWggggPgggTTTTTTTTWW',
        'WgggggPgggTTTKKTTWWW',
        'WgggggPgggTTTKKTTTTW',
        'WgggggPggSgTTTTTTTTW',
        'WgggggPgggggTTTTTTTW',
        'WTggggPPPPggTTTTTTTW',
        'WTTggggggPgggTTTTTTW',
        'WTTTTgggyPygggTTTTTW',
        'WWWWWWWWWPWWWWWWWWWW',
      ],
      encounters: [ { id: 'kinomushi', level: [6, 8], weight: 3 }, { id: 'kinomino', level: [7, 9], weight: 3 }, { id: 'nyakimino', level: [7, 9], weight: 2 }, { id: 'bubu', level: [7, 9], weight: 2 }, { id: 'honeybal', level: [7, 9], weight: 2 } ],
      bunker: [ { id: 'bankani', level: [7, 9], weight: 5 }, { id: 'kokemogu', level: [7, 9], weight: 2 } ],
      events: [
        { x: 9, y: 17, kind: 'warp', to: { map: 'plaza', x: 18, y: 6, dir: 'left' } },
        { x: 17, y: 0, kind: 'warp', to: { map: 'course5', x: 11, y: 14, dir: 'up' } },
        { x: 9, y: 12, kind: 'sign', text: '7番ホール PAR5 林間\n林の おくは OB。強い モンスターに 注意' },
        { x: 3, y: 2, kind: 'item', item: 'ガッツボール', n: 3, flag: 'c3ball', text: '林の かげに ガッツボールが 3つ！' },
        { x: 13, y: 6, kind: 'npc', img: 'v24', sprite: 'npc_woman', dir: 'down', name: 'キャディ',
          text: 'この先の 林間は モンスターが 多いの。\nカート道なりに 北へ すすめば 丘の コースよ。' },
      ],
    },
    course4: {
      greens: [[[8.5, 2.6, 5.6, 2.5], [5.6, 3.4, 3.2, 2.1]]], golf: true, name: 'ガーデンCC 18番（最終ホール）', bgm: 'town', battleBg: 'rough',
      // 長い フェアウェイの 先に 荒れた グリーン。いちばん奥（旗の上）が 調査ポイント
      rows: [
        'WWWWWWWWWWWWWWWWWW',
        'WWgggnnnnnnngggWWW',
        'WgggnnnnnnYnngggWW',
        'WgggnnnnnnnnngggTW',
        'WTggggnnnnnggggTTW',
        'WTTTggggggggggTTTW',
        'WTTKKKggggggKKKTTW',
        'WTTKKKgggggTKKKTTW',
        'WTTKKKTTTTTTKKKTTW',
        'WTTTTTTTTTTTTTTTTW',
        'WgFggggTTTTggggFgW',
        'WgggTTggTTggTTgggW',
        'WgggTTggggggTTgggW',
        'PPPPPPPggggPPPPPPP',
        'WggggggggggggggggW',
        'WgggggggTTgggggggW',
        'WWWWWWWWWWWWWWWWWW',
      ],
      encounters: [ { id: 'shibatta', level: [7, 9], weight: 3 }, { id: 'kokemogu', level: [7, 9], weight: 3 }, { id: 'honeybal', level: [7, 9], weight: 3 }, { id: 'kinomino', level: [7, 9], weight: 2 } ],
      bunker: [ { id: 'bankani', level: [8, 10], weight: 6 } ],
      events: [
        { x: 0, y: 13, kind: 'warp', to: { map: 'course2', x: 16, y: 1, dir: 'down' } },
        { x: 17, y: 13, kind: 'warp', to: { map: 'course5', x: 1, y: 3, dir: 'right' } },
        { x: 9, y: 15, kind: 'sign', text: '18番ホール 最終\n← 池コース ／ 丘コース →' },
        { x: 8, y: 1, kind: 'trigger', id: 'gardenSound' },
        { x: 8, y: 3, kind: 'look', text: '18番グリーン。\n芝が ところどころ 枯れている…。' },
        { x: 4, y: 7, kind: 'look', text: 'バンカーの 砂が 黒ずんでいる。' },
        { x: 13, y: 11, kind: 'look', text: 'ラフ。地面が かすかに ふるえている？' },
        { x: 14, y: 2, kind: 'item', item: 'きずぐすり', n: 1, flag: 'c4heal', text: 'グリーンの わきに きずぐすり！' },
      ],
    },
    heal2: {
      name: 'かいふくの いえ', indoor: true, bgm: 'town',
      rows: [
        'XXXXXXXXXX',
        'X........X',
        'X...s..p.X',
        'XCCCCCCCCX',
        'X........X',
        'X....m...X',
        'XXXXXXXXXX',
      ],
      events: [
        { x: 5, y: 5, kind: 'warp', to: { map: 'town2', x: 3, y: 3, dir: 'down' } },
        { x: 4, y: 2, kind: 'npc', img: 'v12', sprite: 'npc_nurse', dir: 'down', heal: true, name: 'うけつけ',
          text: 'ようこそ ガーデンプレースの かいふくの いえへ。\nなかまを げんきに してあげますね。' },
      ],
    },
    shop2: {
      name: 'ショップ', indoor: true, bgm: 'town',
      rows: [
        'XXXXXXXXXX',
        'X........X',
        'X..s...s.X',
        'XCCCCCCCCX',
        'X........X',
        'X....m...X',
        'XXXXXXXXXX',
      ],
      events: [
        { x: 5, y: 5, kind: 'warp', to: { map: 'town2', x: 3, y: 8, dir: 'down' } },
        { x: 4, y: 2, kind: 'npc', img: 'v25', sprite: 'npc_woman', dir: 'down', name: 'てんいん', shop: true,
          text: 'いらっしゃい！\n森を ぬけてきた お客さんは ひさしぶり。（ショップは じゅんびちゅう）' },
      ],
    },
    house2: {
      name: 'キャディの いえ', indoor: true, bgm: 'town',
      rows: [
        'XXXXXXXXXX',
        'X.s....t.X',
        'X........X',
        'X..O.....X',
        'X........X',
        'Xp.......X',
        'X....m...X',
        'XXXXXXXXXX',
      ],
      events: [
        { x: 5, y: 6, kind: 'warp', to: { map: 'town2', x: 16, y: 3, dir: 'down' } },
        { x: 6, y: 3, kind: 'npc', img: 'v05', sprite: 'npc_man', dir: 'left', name: 'おじいさん',
          text: 'わしは むかし ゴルフ場で\nキャディを しておった。\nガッツモンスターは ゴルフの魂が\nやどった いきものじゃよ。' },
        { x: 7, y: 1, kind: 'look', text: 'テレビ。むかしの ゴルフ大会の\nビデオが ながれている。' },
      ],
    },
  },
};

// 戦闘は 1匹（先頭の なかま）で戦う。HPは 1匹ずつ持つ
const Party = {
  active: st => st.party[0] || null,
  maxHp: st => st.party[0] ? st.party[0].maxHp : 0,
  hp: st => st.party[0] ? Math.max(0, Math.min(st.party[0].maxHp, st.party[0].hp)) : 0,
  set(st, v) { const m = st.party[0]; if (m) m.hp = Math.max(0, Math.min(m.maxHp, Math.round(v))); },
  full(st) { st.party.forEach(m => { m.hp = m.maxHp; m.moves && m.moves.forEach(mv => { mv.pp = mv.maxPp; }); }); },
  def: st => st.party[0] ? st.party[0].def : 5,
  spd: st => st.party[0] ? st.party[0].spd : 5,
};

// ---- 技チャージ（全モンスター共通の標準値：小1・中3・強5・防御2・回復1）。たまった技は自動で発動する ----
//   ボールの色は自分のタイプの「濃い＝強／基本＝中／明るい＝小」、白＝防御、ピンク＝回復
const SKILL_NEED = { small: 1, mid: 3, strong: 5, guard: 2, heal: 1 };   // 回復も1チャージ（ピンク3つ）でたまったら自動で発動
const SKILL_HEAL = 0.25;   // 回復量（最大HPに対する割合）
const SKILL_POWER = { small: 35, mid: 65, strong: 120 };
// タイプごとの技名（仮）。防御は全員「ガード」、回復は「かいふく」で統一。攻撃技を個別に変えたいモンスターは SKILL_OVERRIDE に
const TYPE_SKILLS = {
  'くさ':   { small: 'このは',     mid: 'リーフカッター',  strong: 'グリーンバースト', guard: 'ガード' },
  'ほのお': { small: 'ひのこ',     mid: 'ファイアクロー',  strong: 'ヒートブラスト',   guard: 'ねっきのまく' },
  'みず':   { small: 'しぶき',     mid: 'アクアスラッシュ', strong: 'ビッグウェーブ',  guard: 'みずのベール' },
  'でんき': { small: 'スパーク',   mid: 'でんげきアーム',  strong: 'サンダーブレイク', guard: 'ガード' },
  'じめん': { small: 'つちけむり', mid: 'ロックスロー',    strong: 'グランドクエイク', guard: 'ガード' },
  'かぜ':   { small: 'そよかぜ',   mid: 'ウインドカッター', strong: 'テンペスト',      guard: 'かぜのまく' },
  'ひかり': { small: 'ひかりのつぶ', mid: 'シャインレイ',  strong: 'セイントフラッシュ', guard: 'ガード' },
  'やみ':   { small: 'かげつき',   mid: 'ダークスラッシュ', strong: 'ナイトメアブロー', guard: 'ガード' },
  'ノーマル': { small: 'たいあたり', mid: 'ガッツアタック', strong: 'フルスイング',     guard: 'ガード' },
};
const SKILL_OVERRIDE = {
  bubu: { small: 'かみつく', mid: 'クラウンヘッド', strong: 'キングスマッシュ' },
};
function skillsOf(m) { const t = TYPE_SKILLS[m.type] || TYPE_SKILLS['ノーマル']; return Object.assign({}, t, SKILL_OVERRIDE[m.id] || {}); }

function makeMonster(id, level) {
  const sp = DATA.MONSTERS[id];
  const stat = b => Math.floor(((b * 2) * level) / 100) + 5;
  const hp = Math.floor(((sp.base.hp * 2) * level) / 100) + level + 10;
  return {
    id, level, name: sp.name, type: sp.type,
    maxHp: hp, hp,
    atk: stat(sp.base.atk), def: stat(sp.base.def), spd: stat(sp.base.spd),
    moves: sp.moves.map(m => ({ name: m, pp: DATA.MOVES[m].pp, maxPp: DATA.MOVES[m].pp })),
    exp: 0,
  };
}
