// ============================================================
// 図鑑データ（GUTS MONSTERS 全150匹 + 特別枠）
//   図鑑画像の番号順。stage: 1=初期 2=第2 3=最終。evo: 進化先ID/レベル。
//   ステータスは stage から自動生成（後で個別調整可）。
// ============================================================
// 使用するモンスター。null にすると図鑑の全員が使われる。
//   （2026-09-28：御三家以外はいったん外す。新しいドット絵ができた個体から追加していく）
const DEX_ENABLED = ['kokegame', 'morigame', 'nushigame', 'hinoshishi', 'shishiburn', 'shishivolke', 'amepiyo', 'amegamo', 'doshagamo', 'bubu', 'mantou', 'bankani', 'oobankani', 'shibatta', 'rafubatta', 'shigebatta'];

const DEX = [
  // ---- 御三家 ----
  { no: 1, id: 'kokegame',   name: 'コケガメ',   type: 'くさ',   stage: 1, evo: ['morigame', 14] },
  { no: 2, id: 'morigame',   name: 'モリガメ',   type: 'くさ',   stage: 2, evo: ['nushigame', 28] },
  { no: 3, id: 'nushigame',  name: 'ヌシガメ',   type: 'くさ',   stage: 3 },
  { no: 4, id: 'hinoshishi', name: 'ヒノシシ',   type: 'ほのお', stage: 1, evo: ['shishiburn', 14] },
  { no: 5, id: 'shishiburn', name: 'シシバーン', type: 'ほのお', stage: 2, evo: ['shishivolke', 28] },
  { no: 6, id: 'shishivolke',name: 'シシボルケ', type: 'ほのお', stage: 3 },
  { no: 7, id: 'amepiyo',    name: 'アメピヨ',   type: 'みず',   stage: 1, evo: ['amegamo', 14] },
  { no: 8, id: 'amegamo',    name: 'アメガモ',   type: 'みず',   stage: 2, evo: ['doshagamo', 28] },
  { no: 9, id: 'doshagamo',  name: 'ドシャガモ', type: 'みず',   stage: 3 },
  // ---- くさ ----
  { no: 10, id: 'kokemogu',   name: 'コケモグ',     type: 'くさ', stage: 1, evo: ['rafumoggu', 16] },
  { no: 11, id: 'rafumoggu',  name: 'ラフモッグ',   type: 'くさ', stage: 2, evo: ['mogujuou', 32] },
  { no: 12, id: 'mogujuou',   name: 'モグジュオウ', type: 'くさ', stage: 3 },
  { no: 13, id: 'shibatta',   name: 'シバッタ',     type: 'くさ', stage: 1, evo: ['rafubatta', 15] },
  { no: 14, id: 'rafubatta',  name: 'ラフバッタ',   type: 'くさ', stage: 2, evo: ['shigebatta', 30] },
  { no: 15, id: 'shigebatta', name: 'シゲバッタ',   type: 'くさ', stage: 3 },
  { no: 16, id: 'yotsubausa', name: 'ヨツバウサ',   type: 'くさ', stage: 1, evo: ['clovernny', 18] },
  { no: 17, id: 'clovernny',  name: 'クローバニー', type: 'くさ', stage: 2 },
  { no: 18, id: 'happachi',   name: 'ハッパチ',     type: 'くさ', stage: 1, evo: ['hachibana', 16] },
  { no: 19, id: 'hachibana',  name: 'ハチバナ',     type: 'くさ', stage: 2, evo: ['hanabachion', 32] },
  { no: 20, id: 'hanabachion',name: 'ハナバチオン', type: 'くさ', stage: 3 },
  { no: 21, id: 'matsurisu',  name: 'マツリス',     type: 'くさ', stage: 1, evo: ['matsuborisu', 16] },
  { no: 22, id: 'matsuborisu',name: 'マツボリス',   type: 'くさ', stage: 2, evo: ['matsuboking', 34] },
  { no: 23, id: 'matsuboking',name: 'マツボキング', type: 'くさ', stage: 3 },
  { no: 24, id: 'donglisu',   name: 'ドングリス',   type: 'くさ', stage: 1, evo: ['donglion', 20] },
  { no: 25, id: 'donglion',   name: 'ドングリオン', type: 'くさ', stage: 2 },
  { no: 26, id: 'kameri',     name: 'カメリ',       type: 'くさ', stage: 1, evo: ['camellia', 22] },
  { no: 27, id: 'camellia',   name: 'カメリア',     type: 'くさ', stage: 2 },
  { no: 28, id: 'nidomu',     name: 'ニドム',       type: 'くさ', stage: 1 },
  { no: 29, id: 'nasu',       name: 'ナス',         type: 'くさ', stage: 1 },
  { no: 30, id: 'ibaraki',    name: 'イバラキ',     type: 'くさ', stage: 1 },
  { no: 31, id: 'sayama',     name: 'サヤマ',       type: 'くさ', stage: 1 },
  { no: 32, id: 'hannou',     name: 'ハンノウ',     type: 'くさ', stage: 1 },
  { no: 33, id: 'miyoshi',    name: 'ミヨシ',       type: 'くさ', stage: 1 },
  { no: 34, id: 'asakura',    name: 'アサクラ',     type: 'くさ', stage: 1 },
  // ---- ほのお ----
  { no: 35, id: 'atsuzemi',   name: 'アツゼミ',     type: 'ほのお', stage: 1, evo: ['netsuzemi', 16] },
  { no: 36, id: 'netsuzemi',  name: 'ネツゼミ',     type: 'ほのお', stage: 2, evo: ['magmazemi', 32] },
  { no: 37, id: 'magmazemi',  name: 'マグマゼミ',   type: 'ほのお', stage: 3 },
  { no: 38, id: 'hikabuto',   name: 'ヒカブト',     type: 'ほのお', stage: 1, evo: ['honokabu', 16] },
  { no: 39, id: 'honokabu',   name: 'ホノカブ',     type: 'ほのお', stage: 2, evo: ['magukabuto', 32] },
  { no: 40, id: 'magukabuto', name: 'マグカブト',   type: 'ほのお', stage: 3 },
  { no: 41, id: 'kaledo',     name: 'カレド',       type: 'ほのお', stage: 1, evo: ['kaledoni', 16] },
  { no: 42, id: 'kaledoni',   name: 'カレドニ',     type: 'ほのお', stage: 2, evo: ['kaledonian', 34] },
  { no: 43, id: 'kaledonian', name: 'カレドニアン', type: 'ほのお', stage: 3 },
  { no: 44, id: 'sanhiru',    name: 'サンヒル',     type: 'ほのお', stage: 1, evo: ['sanhiruzu', 18] },
  { no: 45, id: 'sanhiruzu',  name: 'サンヒルズ',   type: 'ほのお', stage: 2 },
  { no: 46, id: 'hirono',     name: 'ヒロノ',       type: 'ほのお', stage: 1, evo: ['akagi', 20] },
  { no: 47, id: 'akagi',      name: 'アカギ',       type: 'ほのお', stage: 2 },
  { no: 48.1, id: 'f_donguris', name: 'ヤングリス', type: 'ほのお', stage: 1 },
  { no: 48.2, id: 'f_donguris2',name: 'ドングリス', type: 'ほのお', stage: 1 },
  { no: 48.3, id: 'f_kanzasho', name: 'カンザショ', type: 'ほのお', stage: 1 },
  { no: 48.4, id: 'f_gimura',   name: 'ギムラ',     type: 'ほのお', stage: 1 },
  { no: 48.5, id: 'f_touma',    name: 'トウマ',     type: 'ほのお', stage: 1 },
  { no: 48.6, id: 'f_akagi2',   name: 'アカギ',     type: 'ほのお', stage: 1 },
  // ---- みず ----
  { no: 48, id: 'mizugamo',   name: 'ミズガモ',     type: 'みず', stage: 1, evo: ['ikegamo', 16] },
  { no: 49, id: 'ikegamo',    name: 'イケガモ',     type: 'みず', stage: 2, evo: ['numagamon', 32] },
  { no: 50, id: 'numagamon',  name: 'ヌマガモン',   type: 'みず', stage: 3 },
  { no: 51, id: 'ikekoi',     name: 'イケコイ',     type: 'みず', stage: 1, evo: ['mizukoi', 16] },
  { no: 52, id: 'mizukoi',    name: 'ミズゴイ',     type: 'みず', stage: 2, evo: ['nushikoi', 32] },
  { no: 53, id: 'nushikoi',   name: 'ヌシゴイ',     type: 'みず', stage: 3 },
  { no: 54, id: 'amekero',    name: 'アメケロ',     type: 'みず', stage: 1, evo: ['doshakero', 16] },
  { no: 55, id: 'doshakero',  name: 'ドシャケロ',   type: 'みず', stage: 2, evo: ['doshakeroro', 32] },
  { no: 56, id: 'doshakeroro',name: 'ドシャケロロ', type: 'みず', stage: 3 },
  { no: 57, id: 'domari',     name: 'ドマリ',       type: 'みず', stage: 1, evo: ['tsudomari', 16] },
  { no: 58, id: 'tsudomari',  name: 'ツドマリ',     type: 'みず', stage: 2, evo: ['natsudomari', 32] },
  { no: 59, id: 'natsudomari',name: 'ナツドマリ',   type: 'みず', stage: 3 },
  { no: 60, id: 'shizu',      name: 'シズ',         type: 'みず', stage: 1, evo: ['shizuhiru', 16] },
  { no: 61, id: 'shizuhiru',  name: 'シズヒル',     type: 'みず', stage: 2, evo: ['shizuhiruzu', 32] },
  { no: 62, id: 'shizuhiruzu',name: 'シズヒルズ',   type: 'みず', stage: 3 },
  { no: 63, id: 'kasumi',     name: 'カスミ',       type: 'みず', stage: 1, evo: ['kasumiga', 16] },
  { no: 64, id: 'kasumiga',   name: 'カスミガ',     type: 'みず', stage: 2, evo: ['kasumigaseki', 32] },
  { no: 65, id: 'kasumigaseki',name:'カスミガセキ', type: 'みず', stage: 3 },
  { no: 66, id: 'arai',       name: 'アライ',       type: 'みず', stage: 1, evo: ['ooarai', 20] },
  { no: 67, id: 'ooarai',     name: 'オオアライ',   type: 'みず', stage: 2 },
  { no: 68, id: 'tone',       name: 'トネ',         type: 'みず', stage: 1, evo: ['ootone', 24] },
  { no: 69, id: 'ootone',     name: 'オオトネ',     type: 'みず', stage: 3 },
  { no: 70, id: 'kawana',     name: 'カワナ',       type: 'みず', stage: 1, evo: ['abiko', 16] },
  { no: 71, id: 'abiko',      name: 'アビコ',       type: 'みず', stage: 2, evo: ['yokohama', 32] },
  { no: 72, id: 'yokohama',   name: 'ヨコハマ',     type: 'みず', stage: 3 },
  { no: 73, id: 'biwako',     name: 'ビワコ',       type: 'みず', stage: 1, evo: ['seta', 16] },
  { no: 74, id: 'seta',       name: 'セタ',         type: 'みず', stage: 2, evo: ['hamano', 32] },
  { no: 75, id: 'hamano',     name: 'ハマノ',       type: 'みず', stage: 3 },
  { no: 76, id: 'hirakawa',   name: 'ヒラカワ',     type: 'みず', stage: 1, evo: ['mishima', 16] },
  { no: 77, id: 'mishima',    name: 'ミシマ',       type: 'みず', stage: 2, evo: ['otaru', 32] },
  { no: 78, id: 'otaru',      name: 'オタル',       type: 'みず', stage: 3 },
  // ---- でんき ----
  { no: 79, id: 'birisu',     name: 'ビリス',       type: 'でんき', stage: 1, evo: ['biririsu', 16] },
  { no: 80, id: 'biririsu',   name: 'ビリリス',     type: 'でんき', stage: 2, evo: ['kaminarisu', 32] },
  { no: 81, id: 'kaminarisu', name: 'カミナリス',   type: 'でんき', stage: 3 },
  { no: 82, id: 'birineko',   name: 'ビリネコ',     type: 'でんき', stage: 1, evo: ['biririneko', 16] },
  { no: 83, id: 'biririneko', name: 'ビリリネコ',   type: 'でんき', stage: 2, evo: ['rainyan', 32] },
  { no: 84, id: 'rainyan',    name: 'ライニャン',   type: 'でんき', stage: 3 },
  { no: 85, id: 'ryuga',      name: 'リュウガ',     type: 'でんき', stage: 1, evo: ['ryugasaki', 22] },
  { no: 86, id: 'ryugasaki',  name: 'リュウガサキ', type: 'でんき', stage: 2 },
  { no: 87, id: 'kogane',     name: 'コガネ',       type: 'でんき', stage: 1, evo: ['koganei', 22] },
  { no: 88, id: 'koganei',    name: 'コガネイ',     type: 'でんき', stage: 2 },
  { no: 89, id: 'nidosaki',   name: 'ニドサキ',     type: 'でんき', stage: 1, evo: ['edosaki', 18] },
  { no: 89.5, id: 'edosaki',  name: 'エドサキ',     type: 'でんき', stage: 2 },
  { no: 90, id: 'resamu',     name: 'レーサム',     type: 'でんき', stage: 1, evo: ['soubu', 22] },
  { no: 91, id: 'soubu',      name: 'ソウブ',       type: 'でんき', stage: 2 },
  // ---- かぜ ----
  { no: 92, id: 'ryuki',      name: 'リュウキ',     type: 'かぜ', stage: 1, evo: ['ryukyu', 22] },
  { no: 93, id: 'ryukyu',     name: 'リュウキュウ', type: 'かぜ', stage: 2 },
  { no: 94, id: 'gaura',      name: 'ガウラ',       type: 'かぜ', stage: 1, evo: ['sodegaura', 22] },
  { no: 95, id: 'sodegaura',  name: 'ソデガウラ',   type: 'かぜ', stage: 2 },
  { no: 96, id: 'basa',       name: 'バサー',       type: 'かぜ', stage: 1, evo: ['basaju', 22] },
  { no: 97, id: 'basaju',     name: 'バサージュ',   type: 'かぜ', stage: 2 },
  { no: 98, id: 'takanodai',  name: 'タカノダイ',   type: 'かぜ', stage: 1, evo: ['narita', 16] },
  { no: 99, id: 'narita',     name: 'ナリタ',       type: 'かぜ', stage: 2, evo: ['bouso', 32] },
  { no: 100, id: 'bouso',     name: 'ボウソウ',     type: 'かぜ', stage: 3 },
  // ---- じめん ----
  { no: 101, id: 'tsuchidango', name: 'ツチダンゴ', type: 'じめん', stage: 1, evo: ['sunadango', 16] },
  { no: 102, id: 'sunadango',   name: 'スナダンゴ', type: 'じめん', stage: 2, evo: ['gandongo', 32] },
  { no: 103, id: 'gandongo',    name: 'ガンドンゴ', type: 'じめん', stage: 3 },
  { no: 104, id: 'anamogu',     name: 'アナモグ',   type: 'じめん', stage: 1, evo: ['horimogu', 16] },
  { no: 105, id: 'horimogu',    name: 'ホリモグ',   type: 'じめん', stage: 2, evo: ['daichimogu', 32] },
  { no: 106, id: 'daichimogu',  name: 'ダイチモグ', type: 'じめん', stage: 3 },
  { no: 107, id: 'bankani',     name: 'バンカニ',   type: 'じめん', stage: 1, evo: ['oobankani', 20] },
  { no: 108, id: 'oobankani',   name: 'オオバンカニ', type: 'じめん', stage: 2 },
  { no: 109, id: 'hakone',      name: 'ハコネ',     type: 'じめん', stage: 1, evo: ['daihakone', 24] },
  { no: 110, id: 'daihakone',   name: 'ダイハコネ', type: 'じめん', stage: 2 },
  { no: 111, id: 'rokku',       name: 'ロック',     type: 'じめん', stage: 1, evo: ['rokkuhiru', 22] },
  { no: 112, id: 'rokkuhiru',   name: 'ロックヒル', type: 'じめん', stage: 2 },
  { no: 113, id: 'yamazu',      name: 'ヤマズ',     type: 'じめん', stage: 1, evo: ['katayamazu', 20] },
  { no: 114, id: 'katayamazu',  name: 'カタヤマズ', type: 'じめん', stage: 2 },
  { no: 115, id: 'dangoru',     name: 'ダンゴル',   type: 'じめん', stage: 1, evo: ['ranzan', 20] },
  { no: 116, id: 'ranzan',      name: 'ランザン',   type: 'じめん', stage: 2 },
  { no: 117, id: 'kyameru',     name: 'キャメル',   type: 'じめん', stage: 1 },
  { no: 118, id: 'musashi',     name: 'ムサシ',     type: 'じめん', stage: 1 },
  { no: 119, id: 'rokkou',      name: 'ロッコウ',   type: 'じめん', stage: 1 },
  { no: 120, id: 'katsuragi',   name: 'カツラギ',   type: 'じめん', stage: 1 },
  // ---- ひかり ----
  { no: 121, id: 'nuveru',   name: 'ヌーヴェル', type: 'ひかり', stage: 1, evo: ['deista', 18] },
  { no: 122, id: 'deista',   name: 'デイスター', type: 'ひかり', stage: 2, evo: ['hourai', 36] },
  { no: 123, id: 'hourai',   name: 'ホウライ',   type: 'ひかり', stage: 3 },
  { no: 124, id: 'sousei',   name: 'ソウセイ',   type: 'ひかり', stage: 1, evo: ['nikkou', 18] },
  { no: 125, id: 'nikkou',   name: 'ニッコウ',   type: 'ひかり', stage: 2, evo: ['sankou', 36] },
  { no: 126, id: 'sankou',   name: 'サンコウ',   type: 'ひかり', stage: 3 },
  // ---- やみ ----
  { no: 127, id: 'yorukara',   name: 'ヨルカラ',   type: 'やみ', stage: 1, evo: ['kurogara', 18] },
  { no: 128, id: 'kurogara',   name: 'クロガラ',   type: 'やみ', stage: 2, evo: ['yamigarasu', 36] },
  { no: 129, id: 'yamigarasu', name: 'ヤミガラス', type: 'やみ', stage: 3 },
  { no: 130, id: 'gasaki',     name: 'ガサキ',     type: 'やみ', stage: 1, evo: ['anegasaki', 18] },
  { no: 131, id: 'anegasaki',  name: 'アネガサキ', type: 'やみ', stage: 2, evo: ['maguregar', 36] },
  { no: 132, id: 'maguregar',  name: 'マグレガー', type: 'やみ', stage: 3 },
  { no: 133, id: 'berseruba',  name: 'ベルセルバ', type: 'やみ', stage: 2, evo: ['yomiuri', 36] },
  { no: 134, id: 'yomiuri',    name: 'ヨミウリ',   type: 'やみ', stage: 3 },
  // ---- ノーマル ----
  { no: 135, id: 'hatakon',  name: 'ハタコン',   type: 'ノーマル', stage: 1, evo: ['binkon', 12] },
  { no: 136, id: 'binkon',   name: 'ビンコン',   type: 'ノーマル', stage: 2, evo: ['tanugoru', 24] },
  { no: 139, id: 'tanugoru', name: 'タヌゴル',   type: 'ノーマル', stage: 2, evo: ['tanuking', 36] },
  { no: 140, id: 'tanuking', name: 'タヌキング', type: 'ノーマル', stage: 3 },
  { no: 141, id: 'sagami',   name: 'サガミ',     type: 'ノーマル', stage: 1, evo: ['totsuka', 14] },
  { no: 142, id: 'totsuka',  name: 'トツカ',     type: 'ノーマル', stage: 2, evo: ['fuchu', 26] },
  { no: 143, id: 'fuchu',    name: 'フチュウ',   type: 'ノーマル', stage: 2, evo: ['wagou', 34] },
  { no: 144, id: 'wagou',    name: 'ワゴウ',     type: 'ノーマル', stage: 3, evo: ['koga', 42] },
  { no: 145, id: 'koga',     name: 'コガ',       type: 'ノーマル', stage: 3 },
  // ---- 特別枠 ----
  { no: 146, id: 'bubu',   name: 'ブブ',     type: 'ノーマル', stage: 2, special: true },
  { no: 147, id: 'mantou', name: 'マントウ', type: 'ノーマル', stage: 2, special: true },
];

// タイプ相性（攻撃側→防御側）。未定義は1倍。
const TYPE_CHART = {
  'くさ':   { 'みず': 2, 'じめん': 2, 'ほのお': 0.5, 'かぜ': 0.5 },
  'ほのお': { 'くさ': 2, 'みず': 0.5, 'じめん': 0.5 },
  'みず':   { 'ほのお': 2, 'じめん': 2, 'くさ': 0.5, 'でんき': 0.5 },
  'でんき': { 'みず': 2, 'かぜ': 2, 'じめん': 0, 'くさ': 0.5 },
  'かぜ':   { 'くさ': 2, 'でんき': 0.5 },
  'じめん': { 'でんき': 2, 'ほのお': 2, 'くさ': 0.5, 'かぜ': 0.5 },
  'ひかり': { 'やみ': 2, 'ひかり': 0.5 },
  'やみ':   { 'ひかり': 2, 'やみ': 0.5 },
  'ノーマル': {},
};

// タイプごとの基本技（初期2つ）
const TYPE_MOVES = {
  'くさ':   ['たいあたり', 'はっぱカッター'], 'ほのお': ['たいあたり', 'ひのこ'], 'みず': ['たいあたり', 'あまごい'],
  'でんき': ['たいあたり', 'でんきショック'], 'かぜ': ['たいあたり', 'かぜおこし'], 'じめん': ['たいあたり', 'すなかけ'],
  'ひかり': ['たいあたり', 'ひかりのつぶ'], 'やみ': ['ひっかく', 'かげうち'], 'ノーマル': ['たいあたり', 'かみつく'],
};
